name: Build main Image

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-sandbox-default:
    uses: mogenius/github-actions/.github/workflows/build-multiarch.yml@f17db5c42b9390bde81a6c5752fbc32cbcff677a # v1.8.5
    secrets: inherit
    with:
      version: "main"
      image: ghcr.io/mogenius/agent-sandbox-chart/sandbox-default
      dockerfile: images/sandbox-default/Dockerfile
      architectures: amd64,arm64
      push_latest: false
